addpath('./ARDMakers')
addpath('./Cancellation')
addpath('./Classes')
addpath('./Input');

clear;
clc;
close all;

%% Processing Parameters:
% Set to 0 to use the RCF file generated by combineRxData.m
hdf5_input = 0;

% The input file created by combineRxData.m
InputRCFFilename = 'Input/JamSingleTarget_fers_latest_low_power_100uw/ArmasuisseJam.rcf';
InputHDF5Filename = 'RecordingName.h5';

% --- Derived CPI Parameters from CleanSingleTarget.ard ---
CPI_s = 4.000; % CPI Duration

% --- Cancellation Settings ---
EnableCancellation = 1;
CancellationMaxRange_m = 85000;
CancallationMaxDoppler_Hz = 5;
CancellationNInterations = 15;
CancellationNSegments = 4;

% --- ARD Coverage Parameters ---
ARDMaxRange_m = 250100;
ARDMaxDoppler_Hz = 200;
TxToReferenceRxDistance_m = 74460;

outputARDPath = './Output';

% Ensure output directory exists
if ~exist(outputARDPath, 'dir')
    mkdir(outputARDPath);
end

if hdf5_input == 1
    % Run the line below to determine which GSNC chunk (GSNC_dataX) to extract
    % whos('-file', InputHDF5Filename)
    fprintf('Reading HDF5 File..\n')
    % Read the data chunk
    load(InputHDF5Filename, 'GSNC_data2', '-mat');
    % Read the sample rate
    load(InputHDF5Filename, 'SR_uHz', '-mat');
    % Read the centre frequency
    load(InputHDF5Filename, 'GCF_uHz', '-mat');
    % Read the bandwidth
    load(InputHDF5Filename, 'GCBW_uHz', '-mat');
    fprintf('HDF5 file read completed\n');

    % Specify the indices of the reference and surveillance channel
    RefChannelIndex = 1;
    SurvChannelIndex = 2;
    RefData = single(GSNC_data2(:,RefChannelIndex));
    SurvData = single(GSNC_data2(:,SurvChannelIndex));
    clear GSNC_data2;

    % Compute the number of samples in the CPI
    CPISize_nSamp = (double(SR_uHz) / 1000000) * CPI_s;
    TotalNumSamples = length(RefData);
else
    fprintf('Opening RCF File: %s\n', InputRCFFilename);
    oInputRCFHeader = cRCF;
    oInputRCFHeader.readHeaderFromFile(InputRCFFilename);

    % Calculate samples per CPI based on the file's actual sample rate
    CPISize_nSamp = floor(oInputRCFHeader.getFs_Hz() * CPI_s);
    TotalNumSamples = oInputRCFHeader.getNSamples();
end

%% Loop per CPI:
nCPIs = floor(TotalNumSamples / CPISize_nSamp);
CPIStartSampleNumber =  0;
CGLSAlpha = 0;

fprintf('Total CPIs to process: %d\n', nCPIs);

DSI_suppression_history = zeros(nCPIs, 1);

for CPINo = 0:nCPIs - 1

    fprintf('Processing CPI %i of %i (Time: %.2fs):\n', CPINo + 1, nCPIs, CPINo * CPI_s);

    %Read data from the RCF or construct a dummy RCF object from the parsed HDF5 data
    if hdf5_input == 1
        oCPIRCF = cRCF;
        oCPIRCF.m_fvReferenceData = RefData(CPIStartSampleNumber + 1 : CPIStartSampleNumber + CPISize_nSamp);
        oCPIRCF.m_fvSurveillanceData = SurvData(CPIStartSampleNumber + 1 : CPIStartSampleNumber + CPISize_nSamp);
        oCPIRCF.m_NSamples = CPISize_nSamp;
        oCPIRCF.m_Fs_Hz = double(SR_uHz) / 1000000;
        oCPIRCF.m_Fc_Hz = (GCF_uHz(1)) / 1000000;
        oCPIRCF.m_Bw_Hz = double(GCBW_uHz) / 1000000;
        oCPIRCF.m_TimeStamp_us = CPIStartSampleNumber * 1000000 / oCPIRCF.m_Fs_Hz;
    else
        oCPIRCF = oInputRCFHeader.readFromFile(InputRCFFilename, CPIStartSampleNumber+1, CPISize_nSamp);
    end

    %Now advance starting sample by 1 CPI for next interation
    CPIStartSampleNumber = CPIStartSampleNumber + CPISize_nSamp;

    if(EnableCancellation)
        fprintf('\tDoing cancellation\n');

        % Store pre-cancellation surveillance data
        preCancelSurv = oCPIRCF.m_fvSurveillanceData;

        % Calculate pre-cancellation power
        preCancelPower = mean(abs(preCancelSurv).^2);

        tic
        [oCPIRCF, CGLSAlpha] = CGLS_Cancellation(oCPIRCF, CancellationMaxRange_m, CancallationMaxDoppler_Hz, TxToReferenceRxDistance_m, CancellationNSegments, CancellationNInterations, CGLSAlpha);
        %oCPIRCF = ECA_Cancellation(oCPIRCF, CancellationMaxRange_m, CancallationMaxDoppler_Hz, TxToReferenceRxDistance_m, CancellationNSegments);
        toc

        % Calculate post-cancellation power
        postCancelPower = mean(abs(oCPIRCF.m_fvSurveillanceData).^2);

        % Calculate DSI suppression in dB
        DSI_suppression_dB = 10 * log10(preCancelPower / postCancelPower);

        DSI_suppression_history(CPINo + 1) = DSI_suppression_dB;
    end

    fprintf('\tDoing range/Doppler processing\n');
    tic
    %oARD = Batches_ARD(oCPIRCF, ARDMaxRange_m, ARDMaxDoppler_Hz, TxToReferenceRxDistance_m);
    oARD = FX_ARD(oCPIRCF, ARDMaxRange_m, ARDMaxDoppler_Hz, TxToReferenceRxDistance_m);
    toc

    %Write ARD to file:
    ARDFilename = outputARDPath;
    if(ARDFilename(length(ARDFilename)) ~= '/')
        ARDFilename = [ARDFilename '/'];
    end

    % ARDFilename = [ARDFilename oARD.timeStampToString(), '.ard'];
    ARDFilename = [ARDFilename num2str(CPINo), '.ard'];

    oARD.writeToFile(ARDFilename);

    fprintf('\n\n');

end

fprintf('\nMean DSI Suppression: %.2f dB\n', mean(DSI_suppression_history));
fprintf('Std Dev: %.2f dB\n', std(DSI_suppression_history));

% print all DSI suppression values
fprintf('DSI Suppression per CPI:\n');
for i = 1:length(DSI_suppression_history)
    fprintf('CPI %d: %.2f dB\n', i, DSI_suppression_history(i));
end