addpath('./ARDMakers')
addpath('./Cancellation')
addpath('./Classes')
addpath('./Input');

clear;
clc;
close all;

%% Processing Parameters:
% Set to 0 to use the RCF file generated by combineRxData.m
hdf5_input = 0;

InputRCFFilename = 'Input/ArmasuisseClean.rcf';
% InputHDF5Filename is ignored when hdf5_input = 0

% CPI Settings
% 0.5s gives 2Hz Doppler resolution.
% T=83s will be found at Index 166 (83 / 0.5)
CPI_s = 0.5;

% Cancellation Settings
% We enable this to remove the Direct Signal (DSI) to lower the noise floor
EnableCancellation = 1;
% Cancellation Range must cover the Baseline (74.5km) + some buffer
CancellationMaxRange_m = 80000;
CancallationMaxDoppler_Hz = 5; % Cancel static/slow clutter (DSI is static geometry)
CancellationNInterations = 10; % CGLS iterations
CancellationNSegments = 4;

% ARD Dimensions
% Target is at ~123km, so we process up to 130km
ARDMaxRange_m = 130000;
% Target is at ~87Hz, so we process up to 100Hz
ARDMaxDoppler_Hz = 100;

% Baseline Geometry Calculation:
% Tx: (258804.41, 6228720.84, 397)
% Rx: (287942.01, 6297267.09, 241)
% Dist = sqrt((dx)^2 + (dy)^2 + (dz)^2) approx 74487m
TxToReferenceRxDistance_m = 74487;

outputARDPath = './Output';

% Ensure output directory exists
if ~exist(outputARDPath, 'dir')
    mkdir(outputARDPath);
end

%% Data Loading Logic
if hdf5_input == 1
    % (HDF5 loading logic omitted for brevity as we are using RCF mode)
    fprintf('Error: Script configured for HDF5 but RCF mode required.\n');
    return;
else
    fprintf('Opening RCF File: %s\n', InputRCFFilename);
    oInputRCFHeader = cRCF;
    oInputRCFHeader.readHeaderFromFile(InputRCFFilename);

    CPISize_nSamp = floor(oInputRCFHeader.getFs_Hz() * CPI_s);
    TotalNumSamples = oInputRCFHeader.getNSamples();
end

%% Loop per CPI:
nCPIs = floor(TotalNumSamples / CPISize_nSamp);
CPIStartSampleNumber = 0;
CGLSAlpha = 0;

fprintf('Total CPIs to process: %d\n', nCPIs);

for CPINo = 0:nCPIs - 1

    fprintf('Processing CPI %i of %i (Time: %.2fs):\n', CPINo + 1, nCPIs, CPINo * CPI_s);

    % Read data from the RCF
    oCPIRCF = oInputRCFHeader.readFromFile(InputRCFFilename, CPIStartSampleNumber+1, CPISize_nSamp);

    % Advance starting sample
    CPIStartSampleNumber = CPIStartSampleNumber + CPISize_nSamp;

    if(EnableCancellation)
        fprintf('\tDoing cancellation...\n');
        % Note: CGLS is used to remove the strong direct signal at ~74km
        [oCPIRCF, CGLSAlpha] = CGLS_Cancellation(oCPIRCF, CancellationMaxRange_m, CancallationMaxDoppler_Hz, TxToReferenceRxDistance_m, CancellationNSegments, CancellationNInterations, CGLSAlpha);
    end

    fprintf('\tDoing range/Doppler processing...\n');
    % FX_ARD is generally faster for these dimensions
    oARD = FX_ARD(oCPIRCF, ARDMaxRange_m, ARDMaxDoppler_Hz, TxToReferenceRxDistance_m);

    % Write ARD to file
    ARDFilename = outputARDPath;
    if(ARDFilename(length(ARDFilename)) ~= '/')
        ARDFilename = [ARDFilename '/'];
    end

    ARDFilename = [ARDFilename num2str(CPINo), '.ard'];
    oARD.writeToFile(ARDFilename);

    fprintf('\n');
end